"""initial clinical schema

Revision ID: 567e1cd267bb
Revises:
Create Date: 2026-10-04 11:23:51.411335

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "567e1cd267bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.String(length=32), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=32), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_log_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_created_at"), ["created_at"], unique=False)

    op.create_table(
        "location_climate",
        sa.Column("cell", sa.String(length=32), nullable=False),
        sa.Column("annual_precip_mm", sa.Float(), nullable=False),
        sa.Column("mean_rh", sa.Float(), nullable=False),
        sa.Column("mean_temp_c", sa.Float(), nullable=False),
        sa.Column("desha", sa.String(length=16), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cell"),
    )
    op.create_table(
        "model_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.Column("pack_version", sa.String(length=32), nullable=False),
        sa.Column("n_cases", sa.Integer(), nullable=False),
        sa.Column("case_ids", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_model_versions_active"), ["active"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("registration_number", sa.String(length=64), nullable=True),
        sa.Column("practitioner_verified", sa.Boolean(), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_users_role"), ["role"], unique=False)

    op.create_table(
        "consents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("purpose", sa.String(length=32), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_consents_user_id"), ["user_id"], unique=False)

    op.create_table(
        "encounters",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("patient_id", sa.String(length=32), nullable=False),
        sa.Column("practitioner_id", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("triage_level", sa.String(length=16), nullable=False),
        sa.Column("chief_complaint", sa.String(length=300), nullable=True),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("assessment", sa.JSON(), nullable=True),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("ritu", sa.String(length=16), nullable=True),
        sa.Column("desha", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["patient_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["practitioner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_encounters_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_encounters_patient_id"), ["patient_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_encounters_practitioner_id"), ["practitioner_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_encounters_status"), ["status"], unique=False)

    op.create_table(
        "patient_profiles",
        sa.Column("user_id", sa.String(length=32), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("sex", sa.String(length=8), nullable=True),
        sa.Column("state", sa.String(length=64), nullable=True),
        sa.Column("district", sa.String(length=64), nullable=True),
        sa.Column("lat_round", sa.Float(), nullable=True),
        sa.Column("lon_round", sa.Float(), nullable=True),
        sa.Column("desha", sa.String(length=16), nullable=True),
        sa.Column("climate", sa.JSON(), nullable=True),
        sa.Column("prakriti_answers", sa.JSON(), nullable=True),
        sa.Column("prakriti_result", sa.JSON(), nullable=True),
        sa.Column("chronic_conditions", sa.JSON(), nullable=True),
        sa.Column("current_medicines", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("encounter_id", sa.String(length=32), nullable=False),
        sa.Column("practitioner_id", sa.String(length=32), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("condition_id", sa.String(length=16), nullable=True),
        sa.Column("condition_name", sa.String(length=200), nullable=True),
        sa.Column("examination", sa.JSON(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("plan", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["encounter_id"], ["encounters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["practitioner_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_encounter_id"), ["encounter_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_encounter_id"))

    op.drop_table("reviews")
    op.drop_table("patient_profiles")
    with op.batch_alter_table("encounters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_encounters_status"))
        batch_op.drop_index(batch_op.f("ix_encounters_practitioner_id"))
        batch_op.drop_index(batch_op.f("ix_encounters_patient_id"))
        batch_op.drop_index(batch_op.f("ix_encounters_created_at"))

    op.drop_table("encounters")
    with op.batch_alter_table("consents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consents_user_id"))

    op.drop_table("consents")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_role"))
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    with op.batch_alter_table("model_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_model_versions_active"))

    op.drop_table("model_versions")
    op.drop_table("location_climate")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_log_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_log_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_action"))

    op.drop_table("audit_log")
    # ### end Alembic commands ###
