"""ayurveda modules, daily logs, digilocker

Revision ID: 8533fcff7d8f
Revises: 567e1cd267bb
Create Date: 2026-10-04 17:12:11.589969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8533fcff7d8f'
down_revision: Union[str, Sequence[str], None] = '567e1cd267bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('dinacharya', sa.JSON(), nullable=False),
    sa.Column('meals', sa.JSON(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'day', name='uq_daily_user_day')
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_logs_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('return_to', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('state')
    )
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modules', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('identity', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_profiles', schema=None) as batch_op:
        batch_op.drop_column('identity')
        batch_op.drop_column('modules')

    op.drop_table('oauth_states')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_day'))

    op.drop_table('daily_logs')
    # ### end Alembic commands ###
